### ISSUE TITLE
Number of nodes after conv layer seems wrong.

### ISSUE THREAD

**Issue by mahendrakariya** [aamini/introtodeeplearning_labs#13]
In Lab 2 part 1, the formula for calculating `the number of nodes in a feature map after a convolution or a pooling operation` is given as `n = (((d - i + 2p) / s) + 1)^2)`. Shouldn't it be without the `square` operation?

**Comment by aamini** [comment]
The notation was referring to a each dimension individually (so not squaring the two terms). Instead we were writing the dimension of the output feature map as (height_dimension) x (width_dimension) where both height and width can be written as functions of the form: 
`((d - i + 2p) / s) + 1)`

**Comment by mahendrakariya** [comment]
Aah ok! Sorry for the confusion.
