### ISSUE TITLE
Python-midi not available for Python 3.6.5

### ISSUE THREAD

**Issue by srungta** [aamini/introtodeeplearning_labs#17]
I have a miniconda installation with Python3.6.5.
I tried installing python-midi using pip.
The package fails with an error.
```
 Using cached https://files.pythonhosted.org/packages/8d/e1/fd34aa05508d907449fb2d66a679d4f98eeeacdb4b3c7e6af87d91c4fa21/python-midi-v0.2.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\shrung\AppData\Local\Temp\pip-install-jyfi7tsr\python-midi\setup.py", line 42
        print "No sequencer available for '%s' platform." % platform
                                                        ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("No sequencer available for '%s' platform." % platform)?

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\shrung\AppData\Local\Temp\pip-install-jyfi7tsr\python-midi\
```
I have a few questions:

1. Is there a plan to add python 3 support to labs.
2. Any alternate to python midi that is recommended?

**Comment by aamini** [comment]
The lab docker image comes preinstalled with python-midi as well as all other dependencies. We recommend you use this image as outlined on the README.md. 

The problem you have mentioned is a known issue with python-midi and has been reported here: https://github.com/vishnubob/python-midi/issues/145

**Comment by aamini** [comment]
The relevant pull request is here: https://github.com/vishnubob/python-midi/pull/130
