### ISSUE TITLE
Jupyter notebook does not open

### ISSUE THREAD

**Issue by JanVanIm** [aamini/introtodeeplearning_labs#19]
Hello,

After running the command 
`docker run -p 8888:8888 -p 6006:6006 -v /c//Users/User/Documents/MachineLearning/introtodeeplearning_labs-master:/notebooks/introtodeeplearning_labs mit6s191/iap2018:labs`

 where the github repository is in the `MachineLearning` folder,  I got naturally the  message

```
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=63b505ca3081282bfd714df2036be073b825e7b07cc073b1
```

Then I followed the step 9 of [the tutorial on Docker](https://github.com/aamini/introtodeeplearning_labs/blob/master/WindowsDocker.md)  which is to replace `localhost` with the IP of the machine `192.168.99.100`. So in the Edge browser I run 

`http://192.168.99.100:8888/?token=63b505ca3081282bfd714df2036be073b825e7b07cc073b1` 

But I got the error message "we can't reach this page"

Is there something that I did wrong ?

**Comment by aamini** [comment]
Closing this issue since we are releasing new labs which do not use docker and wont have this problem.
