### ISSUE TITLE
Lab1 - Part1 - Section 1.2:Error when using tf.constant to provide input to Keras model.predict

### ISSUE THREAD

**Issue by sibyjackgrove** [aamini/introtodeeplearning_labs#22]
I am encountering an `InvalidArgumentError `error when I use Keras model.predict with tf.constant as input. I am not sure  whether it's because model.predict don't work with tf.constant or I am doing something wrong. It work fine when I use numpy array with same argument.
```
# Define the number of inputs and outputs
n_input_nodes = 2
n_output_nodes = 3

# First define the model 
model = Sequential()

'''TODO: Define a dense (fully connected) layer to compute z'''
# Remember: dense layers are defined by the parameters W and b!
# You can read more about the initialization of W and b in the TF documentation :) 
dense_layer = Dense(n_output_nodes, input_shape=(n_input_nodes,),activation='sigmoid') # TODO 

# Add the dense layer to the model
model.add(dense_layer)
```
Now when I do prediction using:
```
# Test model with example input
x_input = tf.constant([[1.0,2.]], shape=(1,2))
'''TODO: feed input into the model and predict the output!'''
print(model.predict(x_input)) # TODO
```
I get following error:

> InvalidArgumentError: In[0] is not a matrix. Instead it has shape [2]
> 	 [[{{node MatMul_3}}]] [Op:StatefulPartitionedCall]

When I use Numpy array, it works:
```
# Test model with example input
x_input =np.array([[1.0,2.]])
'''TODO: feed input into the model and predict the output!'''
print(model.predict(x_input)) # TODO
```

> [[0.19114174 0.88079417 0.8062956 ]]

Could you let me know if it is a tf issue. If so I can raise an issue on the tf repository.

**Comment by aamini** [comment]
This is very interesting and indeed something that we also observed when making this lab. To make matters worse, the error message that tf provides is not very revealing in this case. 

Even more interesting to me is that using a tf.constant when just calling the model directly (not using the .predict() function) also works! ie. this code
```
x_input = tf.constant([[1.0,2.]], shape=(1,2))
print(model(x_input))
```
works...

In any case, if this is an issue (it may actually be expected tf behavior under the new 2.0 paradigm), I would recommend it be raised with the tf repository.

**Comment by sibyjackgrove** [comment]
Yes, I noticed that in your solution you use  `model(x_input)` and it works with tf.constant. But it's peculiar that it doesn't work with predict. According to documenation predict should accept both TensorFlow tensors and Numpy arrays. I guess it's worth raising an issue.

**Comment by eiserportilla** [comment]
I found in the keras documentation that predict assume a batch size of 32 by default, as it expects to predict over a huge test dataset. The next line didn't show an error:

print model.predict(x_input,batch_size=1,steps=1)
