### ISSUE TITLE
lab1/Part2 fails assertion for tf version 1.13.0 (Colab is on 1.13.1)

### ISSUE THREAD

**Issue by MaxGhenis** [aamini/introtodeeplearning_labs#26]
Running [lab1/Part2_music_generation.ipynb](https://github.com/aamini/introtodeeplearning_labs/blob/master/lab1/Part2_music_generation.ipynb) fails at the beginning because it requests 1.13.0. Looks like Colab updated to 1.13.1 (I didn't do anything special).
```
is_correct_tf_version = '1.13.0' in tf.__version__
...
AssertionError: Wrong tensorflow version (1.13.1) installed
```

Replacing that with this will work, unless that specific version is important:
```
is_correct_tf_version = tf.__version__ >= '1.13.0'
```

**Comment by iammerrick** [comment]
👋 Hello, future deep learning lab adventurer. Ideally, these notebooks are always up to date or maybe they could include a setup.py file 😉? 

Until then Google Collab allows you to "Copy to drive" and modify the Notebook. In which case you can add a new code block to install a specific version `!pip install tensorflow==1.14`.

![image](https://user-images.githubusercontent.com/109635/67153370-30935b80-f2a5-11e9-8587-610f1dc73424.png)

**Comment by aamini** [comment]
thanks @iammerrick! We're working on revamping these labs for this years version of the course and will be sure to take this into account!

**Comment by iammerrick** [comment]
Thanks @aamini !  So grateful all of this is being made available to the public. ❤️
