### ISSUE TITLE
Can someone please Post code with filled #TODO's 

### ISSUE THREAD

**Issue by Tirthnp** [aamini/introtodeeplearning_labs#33]

**Comment by aamini** [comment]
Solutions for every lab (with filled #TODOs) are in the same directories labeled with `*_solutions.ipynb`

**Comment by Tirthnp** [comment]
I was being dumb. After beating my head around documentation of TensorFlow for one day, I realized it was just there. But Thank You so much for quick response @aamini . It an awesome course.

**Comment by aamini** [comment]
No problem!
