### ISSUE TITLE
Lab 2 Import Regex

### ISSUE THREAD

**Issue by garciagh** [aamini/introtodeeplearning_labs#34]
I am having to import "introtodeeplearning_labs". Has anyone have the same problem?
![Regex error](https://user-images.githubusercontent.com/52216149/60124879-9ab54d00-9758-11e9-9149-c742b7425424.png)

**Comment by aamini** [comment]
I noticed this problem yesterday, it seems like it is a new problem on Colab since the newest version doesn't have regex installed by default. 

You can fix the problem by running `!pip install regex` in the cell above.
