### ISSUE TITLE
Lab2/Part2 Error when calling encoder, decoder functions

### ISSUE THREAD

**Issue by Rohitpandey357** [aamini/introtodeeplearning_labs#38]
Error while calling encode and decoder network functions.
Can't convert type <tuple> to tensors.

**Comment by Rohitpandey357** [comment]
TypeErrorTraceback (most recent call last)
<ipython-input-22-0121f31bca3a> in <module>()
      1 '''TODO: create the encoder and decoder networks'''
----> 2 encoder, inputs, ouputs, pre_flatten_shape = make_face_encoder_network() # TODO
      3 decoder = make_face_decoder_network(pre_flatten_shape) # TODO



560       raise TypeError("Failed to convert object of type %s to Tensor. "
    561                       "Contents: %s. Consider casting elements to a "
--> 562                       "supported type." % (type(values), values))
    563     tensor_proto.string_val.extend(str_values)
    564     return tensor_proto

TypeError: Failed to convert object of type <type 'tuple'> to Tensor. Contents: (Dimension(None), Dimension(100)). Consider casting elements to a supported type.

**Comment by Luca96** [comment]
I think this is a duplicated issue. The solution is provided here https://github.com/aamini/introtodeeplearning_labs/issues/27
