### ISSUE TITLE
Trying to run Docker

### ISSUE THREAD

**Issue by miguelp77** [aamini/introtodeeplearning_labs#4]
Hi

I think that it is a basic step, I was googling about it but i can't find what is 

> the correct path to this github repo

 to be replace in docker command.

Could anyone help me with this?

Thank you in advance
M

**Comment by avidiotic** [comment]
Hey @miguelp77, Its going to be the path to the directory where you have cloned/downloaded this github repo. For example, I downloaded the repo as a folder introtodeeplearning_labs in my Downloads folder. Since I am using my mac, my path to the repo is now ~/Users/avi/Downloads.

**Comment by aamini** [comment]
Sorry for the late reply! Yes like @avidiotic mentioned just replace that path to where ever you download this repo to on your local computer.
