### ISSUE TITLE
invalid bind mount spec, invalid mode: /notebooks/introtodeeplearning_labs

### ISSUE THREAD

**Issue by sameermahajan** [aamini/introtodeeplearning_labs#5]
I am trying to try the notebooks posted here as per the instructions given in the readme here as:

sudo docker run -p 8888:8888 -p 6006:6006 -v https://github.com/aamini/introtodeeplearning_labs:/notebooks/introtodeeplearning_labs mit6s191/iap2018:labs

when I get the error:

docker: Error response from daemon: invalid bind mount spec "https://github.com/aamini/introtodeeplearning_labs:/notebooks/introtodeeplearning_labs": invalid mode: /notebooks/introtodeeplearning_labs.

Am I missing the path for the repo?

**Comment by aamini** [comment]
Also, I would recommend running docker without executing `sudo`

**Comment by aamini** [comment]
In case you're having trouble downloading try clicking the download zip link here: 

![image](https://user-images.githubusercontent.com/5893396/36755634-cb51e9be-1bda-11e8-949e-668ef7b9a55c.png)

**Comment by SameerMahajan-GSLab** [comment]
aamini, 

Thanks for the response. I didn't realize earlier that I could not work with remote repository but had to download it locally  to work  with. With your suggestion  it worked fine. Thanks for the inconvenience.

Sameer
