### ISSUE TITLE
Empty jupyter notbook list

### ISSUE THREAD

**Issue by grasshopyx** [aamini/introtodeeplearning_labs#7]
Hi there!

I use Docker for Mac.

I ran the docker as follows:
`docker run -p 8888:8888 -p 6006:6006 -v introtodeeplearning_labs:/notebooks/introtodeeplearning_labs mit6s191/iap2018:labs`

But when I opened the browser, what I saw is an empty `introtodeepleraning_labs` folder
![image](https://user-images.githubusercontent.com/4454939/38546057-30cf84f8-3cde-11e8-83fe-dcb9c0eb6c85.png)

![image](https://user-images.githubusercontent.com/4454939/38546112-59acd402-3cde-11e8-8967-05f33ac2519f.png)

I couldn't find `lab1` or `lab2` folders. What happened?

Thanks for any response!

**Comment by grasshopyx** [comment]
Problem solved!
I should have used the absolute path instead of relative path.
`docker run -p 8888:8888 -p 6006:6006 -v $PWD/introtodeeplearning_labs:/notebooks/introtodeeplearning_labs mit6s191/iap2018:labs`
It works for me.

**Comment by aamini** [comment]
Awesome! thanks for posting the solution!
